services:
  app:
    image: langflowai/langflow:latest
    restart: always
    ports:
      - "7860:7860"
    volumes:
      - langflow-data:/app/langflow
      - ./config:/app/config
    env_file:
      - .env
    networks:
      - saas-ia-filament_sail
  vectorstore:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: vectorstore
      POSTGRES_PASSWORD: vectorstore
      POSTGRES_DB: vectorstore
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - saas-ia-filament_sail

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - saas-ia-filament_sail

networks:
  saas-ia-filament_sail:
    external: true


volumes:
  langflow-data:
  redis-data:
  pgvector-data: